Equations for do a perfect shot with a bow
PrismarineJS/mineflayer pull request #1351
Opened 2020-10-07 20:16 UTC by sefirosweb

Hello!, I made a package for calculate the yaw and pitch for a bow attack, it also detects movement to anticipate :D

I tried pack to simply files for easy read and use, you can see all https://github.com/sefirosweb/minecraftHawkEye

2020-10-07 20:20 UTC, TheDudeFromCI commented
Looks useful!
You should also add your project to the plugin list in the readme as well.
https://github.com/PrismarineJS/mineflayer/blob/master/docs/README.md

2020-10-07 20:43 UTC, rom1504 commented
can you run npm run fix to fix the linting for your example ?

2020-10-07 20:57 UTC, rom1504 commented
and would be great to do this https://github.com/sefirosweb/minecraftHawkEye/issues/1
(you can check any of the plugins listed in the readme as other examples)

2020-10-07 21:01 UTC, wvffle requested changes

2020-10-07 21:01 UTC, wvffle commented on examples/perfectShotBow.js
> +        return false;
Add `{` and `}`

2020-10-09 22:44 UTC, sefirosweb commented on examples/perfectShotBow.js
> +        return false;
OK! i try to fix this =)

2020-10-12 20:18 UTC, sefirosweb commented
Hi guys I done a update to 1.0.5

Now works has plugin,

Also I fixed some bugs, and now the precision to the target is better :D

2020-10-12 20:47 UTC, TheDudeFromCI commented
Looks good to me.
Just run `npx standard --fix` inside the example code to fix the linting errors so the build will pass.
After that, it should be good to go. :+1:

2020-10-15 19:41 UTC, sefirosweb commented
> Looks good to me.
> Just run `npx standard --fix` inside the example code to fix the linting errors so the build will pass.
> After that, it should be good to go. 👍

Done! you can do double check if fine?

2020-10-15 20:45 UTC, rom1504 commented
you need to push after running it ;)

2020-10-15 22:05 UTC, sefirosweb commented
> you need to push after running it ;)

sorry im stupid =P

Pushed,

Also today had fixed a minor bugs (the height targets, the spiders is too small =P )

2020-10-16 00:06 UTC, TheDudeFromCI approved these changes

2020-10-18 12:12 UTC, rom1504 approved these changes

2020-10-18 12:12 UTC, merged