add uuid by objectUUID as it was missing
PrismarineJS/mineflayer pull request #1411
Opened 2020-10-28 23:08 UTC by Rob9315

I tried reading the UUID of the entity of a dropped Item and it was undefined. this should fix that

2020-10-29 18:31 UTC, wvffle requested changes

2020-10-29 18:31 UTC, wvffle commented on lib/plugins/entities.js
> +    if (packet.objectUUID) entity.uuid = packet.objectUUID
```js
    if (packet.objectUUID) {
      entity.uuid = packet.objectUUID
    }
```

also move it either above or below the assigments with newlines around the if

2020-10-29 20:41 UTC, Rob9315 commented
so now I realized that the "spawn_entity" packet does not have an entityUUID property, it is always objectUUID so now I removed the if statement and just replaced the entityUUID by objectUUID

2020-10-30 15:40 UTC, wvffle commented
Are you sure that previous versions have `objectUUID` instead of `entityUUID` as well?

2020-10-31 15:03 UTC, rom1504 approved these changes

2020-10-31 15:03 UTC, merged