Added better handling for automatic dependency resolution between plugins
PrismarineJS/mineflayer pull request #1412
Opened 2020-10-29 10:55 UTC by TheDudeFromCI

In sitations where Plugin A relies on Plugin B to work, it's useful for plugin A to automatically trigger plugin B to load if the user does not specify this directly. This allows for better API compatibility. (A plugin can add a new plugin dependency to the bot without breaking existing bots that don't load plugin B by default.)

This also makes it much easier to load plugin trees that contain several nested plugins, all by simply loading the parent plugin.

This PR works by safely allowing the `bot.loadPlugin` to be called more than once without actually loading the plugin twice.

Bot:
```js
const { pluginA } = require('mineflayer-plugin-a')
const bot = mineflayer.createBot({...})
bot.loadPlugin(pluginA)
```

Plugin A:
```js
const { pluginB } = require('mineflayer-plugin-b')

function pluginA (bot) {
  bot.loadPlugin(pluginB)

  bot.pluginA = {}
  bot.pluginA.someFunction = function () {}
}

module.exports = {
  pluginA
}
```

Using this, Plugin A can safely load Plugin B when injected. If the user already has PluginB loaded, nothing happens.

2020-10-29 10:55 UTC, TheDudeFromCI commented
I also added the `bot.hasPlugin(plugin)` function that can similarly be used for soft dependencies.

2020-10-29 18:29 UTC, wvffle reviewed
What if `plugin-a` requires `plugin-c@1.0.0` and `plugin-b` requires `plugin-c@2.0.0`?

2020-10-29 21:20 UTC, TheDudeFromCI commented
Obviously two versions of the same plugin usually cannot be loaded at the same time.

The name space wouldn't event allow it unless you wrote something like `bot.myplugin2` for version 2.0.0 or something.

The end user must choose between whether they want to use plugin a or plugin b. Or hopefully convince one of the plugin a or b to add support for both versions and just load the ideal version manually.

2020-10-29 21:30 UTC, TheDudeFromCI commented
Also, wouldn't this kind of issue be resolved by npm, anyway?

2020-10-30 15:36 UTC, wvffle commented
> Also, wouldn't this kind of issue be resolved by npm, anyway?
Don't think so.

2020-10-30 15:37 UTC, wvffle reviewed
> The end user must choose between whether they want to use plugin a or plugin b.

In such case I agree.

2020-10-30 15:38 UTC, wvffle approved these changes
(And I wanted to approve it.)

2020-10-31 15:28 UTC, rom1504 requested changes
this is using the object reference as a plugin key
can you double-check this work in all circumstances?
for example, if you do a require in 2 different files for the plugin, do you get exactly the same reference?

2020-10-31 22:53 UTC, TheDudeFromCI commented
> this is using the object reference as a plugin key
> can you double-check this work in all circumstances?
> for example, if you do a require in 2 different files for the plugin, do you get exactly the same reference?

Yes, I did check.

While it works oin most usecases, I found 2 situations where issues arise.

1) When npm does not de-dupe dependencies and multiple versions of the same library are loaded. This triggers multiple versions of the same object to be generated. This is most commonly caused from people pinning dependencies.

2) When functions are "generated" instead of static.
```js
module.exports = funcition(properties) {
  return function () {
    // stuff
  }
}
```

Ideally, I would _much_ rather use plugin metadata than object reference. (See #1244)
However, until a plugin standard is agreed on and initiated, that's not yet possible.

2020-11-01 14:30 UTC, rom1504 approved these changes

2020-11-01 14:30 UTC, merged