Edited so crafting works on any versions
PrismarineJS/mineflayer pull request #1462
Opened 2020-11-19 14:06 UTC by satyamedh

changed it from hardcoded 58 to get it using minecraft-data lib

2020-11-19 14:10 UTC, TheDudeFromCI requested changes

2020-11-19 14:10 UTC, TheDudeFromCI commented on examples/inventory.js
> +    matching: require('minecraft-data')(bot.version).blocksByName.crafting_table.id
Probably move this to be next to the "item" declaration variable, for readability.
```js
const mcData = require('minecraft-data')(bot.version)

const item = mcData.findItemOrBlockByName(name)
const craftingTableID = mcData.blocksByName.crafting_table.id

const craftingTable = bot.findBlock({
  matching: craftingTableID
})
```

2020-11-19 16:23 UTC, wvffle requested changes

2020-11-19 16:23 UTC, wvffle commented on examples/inventory.js
> +    matching: require('minecraft-data')(bot.version).blocksByName.crafting_table.id
`require('minecraft-data')(bot.version)` is redundant here. Move it to a `mcData` variable, like @TheDudeFromCI proposed

2020-12-05 15:57 UTC, rom1504 commented
@satyamedh could you please apply the proposed suggestions ?

2020-12-23 15:38 UTC, TheDudeFromCI commented
@satyamedh Are you still working on this?

2020-12-28 17:34 UTC, rom1504 commented
merged in https://github.com/PrismarineJS/mineflayer/commit/4846458734d82fe35736541ce16b7ab9a350a088

2020-12-28 17:34 UTC, closed without merging