Add number support to bot.chat
PrismarineJS/mineflayer pull request #1515
Opened 2020-12-20 09:16 UTC by BlueBurgersTDD

2020-12-20 09:17 UTC, BlueBurgersTDD commented
Not tested yet

2020-12-20 11:25 UTC, TheDudeFromCI requested changes

2020-12-20 11:25 UTC, TheDudeFromCI commented on lib/plugins/chat.js
>        throw new Error('Incorrect type! Should be a string.')
Probably change the error message to: 'Incorrect type! Should be a string or number.'

2020-12-20 12:42 UTC, TheDudeFromCI approved these changes

2020-12-21 12:11 UTC, dada513 approved these changes

2020-12-21 16:10 UTC, merged