Better calculation of digging range.
PrismarineJS/mineflayer pull request #1533
Opened 2020-12-24 14:10 UTC by goncharovchik

Before the change, the bot that used `bot.canDigBlock` only dig 4 blocks up, but the player digs 5 up. I tested the function in different directions and achieved a perfect calculation.

2020-12-24 15:22 UTC, TheDudeFromCI requested changes

2020-12-24 15:22 UTC, TheDudeFromCI commented on lib/plugins/digging.js
> +    return block && block.diggable && block.position.offset(0.5, 0.5, 0.5).distanceTo(bot.entity.position.offset(0, 2, 0)) <= 5.2
Use `.offset(0, 1.65, 0)` to use the player's eye height.

2020-12-24 23:39 UTC, TheDudeFromCI approved these changes

2020-12-25 03:53 UTC, wvffle approved these changes

2020-12-25 14:13 UTC, rom1504 commented
Is there any external reference about this ?
This will reduce the digging distance for block that are below, is it expected ?

2020-12-25 16:34 UTC, TheDudeFromCI commented
This implementation is more accurate to vanilla. The old implementation was a poor approximation.

2020-12-25 16:46 UTC, goncharovchik commented
> This implementation is more accurate to vanilla. The old implementation was a poor approximation.

I completely agree. If I'm not mistaken, the player digs 2-3 blocks and presumably a bot with such a change will be ± also

2020-12-25 20:12 UTC, rom1504 commented
ok, would still be great to find any reference confirming this is how it's implemented in vanilla

2020-12-25 20:22 UTC, ph0t0shop commented
Still not completely accurate, since the client ray casts to the block _face_, not just the block. This also means, when looking along the edge of the block, a part of a block face might be within range, while another part of the same face might not be.

2020-12-25 20:27 UTC, Karang commented
To be accurate it should use the raycast iterator, but this is already better than what was before

2020-12-26 16:47 UTC, goncharovchik commented
> Still not completely accurate, since the client ray casts to the block _face_, not just the block. This also means, when looking along the edge of the block, a part of a block face might be within range, while another part of the same face might not be.


hmm, well, it seems that I did 5.1 for this, and not just 5

2020-12-26 16:48 UTC, goncharovchik commented
> To be accurate it should use the raycast iterator, but this is already better than what was before

It seems to me that there may be problems with this. Although. I'll try later

2020-12-28 16:46 UTC, merged