Fishing refactor
PrismarineJS/mineflayer pull request #1621
Opened 2021-01-26 06:06 UTC by extremeheat

2021-01-28 09:11 UTC, rom1504 commented
What are bugs in the current implementation that this is fixing?

2021-01-28 17:59 UTC, extremeheat commented
The purpose of the pr was to make the fishing logic a bit easier to flow/debug. In terms of changes,
* fishing times out on failure, this way if the bot throws somewhere where it can't catch fish, or throwing the bobber fails, the fishing fails as mentioned
* adds a way to cancel fishing that checks if an active bobber was successfully thrown before calling `activateItem()`

```js
const task = bot.fish((err) => {
  if (err) { console.error(err) }
})
// some other code
task.cancel(Error('reason'))

// vs
let fishing = true
bot.fish(() => {
  fishing = false
})
//...
if (fishing) activateItem() // <- can fail
```

also enables behaviors like this:
```js
let keepFishing = true
let task
while (keepFishing) {
    try {
      task = await bot.fish()
      // check for entity spawn and collect fish
    } catch (e) {
        // move away, check rod, etc.
    }
}
keepFishing = true
task.cancel() // can safely cancel no matter state of the fishing rod
```

2021-01-31 12:49 UTC, rom1504 requested changes
I'm not so convinced to extend promise in that way.
Why not instead have a bot.stopFish() ?
It is not possible to fish 2 things at once, so it makes sense mineflayer would handle internally the fishing/not fishing status

2021-01-31 20:35 UTC, extremeheat commented
ok, this was primarily intended to help debug/fix the fishing tests failing so I’ll close it

2021-01-31 20:35 UTC, closed without merging