Added pviewer screenshot.js example
PrismarineJS/mineflayer pull request #1828
Opened 2021-03-31 15:18 UTC by IceTank

A simple screenshot example that joins a server and takes 5 pictures.

Solves https://github.com/PrismarineJS/mineflayer/issues/1562#issue-777556792 

Works for 1.13 or later versions.
Should work for 1.10, 1.11 and 1.12 when https://github.com/PrismarineJS/minecraft-data/issues/386 is merged.

2021-04-01 00:25 UTC, Karang approved these changes

2021-04-01 23:13 UTC, rom1504 requested changes
that's nice but could you put it in a different folder ? node canvas webgl is not easy to install in all platforms so it's good to keep the main viewer example without it

2021-04-02 11:18 UTC, IceTank commented
Moved to new folder and added some installation info to README

2021-04-02 11:21 UTC, rom1504 commented on examples/viewer/package.json
>      "prismarine-viewer": "^1.0.3",
Duplicated

2021-04-02 21:52 UTC, rom1504 approved these changes

2021-04-02 21:52 UTC, merged