Add window parameter for clickWindow function
PrismarineJS/mineflayer pull request #1920
Opened 2021-05-22 06:11 UTC by Camezza

closeWindow has it, so why doesn't this?

By default, clickWindow would use the currently open window or player inventory for packet transactions. By specifying a parameter, windows can be passed down directly from the windowOpen event.

2021-05-30 15:07 UTC, rom1504 requested changes
there can be only one window open
do you want to change that ? there are many more things to do to change this

2021-06-02 21:30 UTC, Camezza commented
No, I only wanted to implement a quick fix for specifying a window to click rather than defaulting to inventory or an unspecific one

2021-06-02 21:48 UTC, u9g commented
> No, I only wanted to implement a quick fix for specifying a window to click rather than defaulting to inventory or an unspecific one

theres no specifying a window. There is always an active window, there can’t be any other windows used at that point. Theres no reason then to worry about other windows if we store the opened window’s id internally.

2021-06-27 03:47 UTC, Camezza commented
Closed as it has been deemed unnecessary

2021-06-27 03:47 UTC, closed without merging