Fix crash on blocks without registered blockId
PrismarineJS/mineflayer pull request #2022
Opened 2021-07-04 01:13 UTC by Furry

A simple addition to the already-existing if statement on line 59 ( !blocks[packet.blockId] ) to ignore handling packets coming from unregistered blocks that may have been introduced by protocol modifications (IE a Forge Protocol Extension, https://www.npmjs.com/package/minecraft-protocol-forge)

2021-07-06 10:59 UTC, rom1504 requested changes

2021-07-06 10:59 UTC, rom1504 commented on lib/plugins/block_actions.js
> +    if (block === null || !blocks[packet.blockId]) { return }
can you add a comment this is for ignore non vanilla blocks ?

2021-07-07 03:27 UTC, Furry commented on lib/plugins/block_actions.js
> +    if (block === null || !blocks[packet.blockId]) { return }
Ignore non-vanilla blocks

2021-07-07 03:36 UTC, Furry commented
Added the comment, sorry if I screwed up the Github flow with it, was abit confusing.

2021-07-07 09:00 UTC, rom1504 approved these changes

2021-07-20 08:50 UTC, rom1504 approved these changes

2021-07-20 08:50 UTC, merged