Add option to bot.look
PrismarineJS/mineflayer pull request #2082
Opened 2021-08-05 22:38 UTC by OofAlt

With the current codebase, when having a control state active and doing a bot.look, the physics simulation snaps the bot's yaw to what was set, rather than the direction the bot sent to the server. This change gives option to let the bot head in the direction it sent to the server.

2021-08-05 22:46 UTC, OofAlt commented
Addresses #2074

2021-08-06 04:00 UTC, OofAlt commented
there seems to be some bugs with set yaw, need to rethink implementation

2021-08-06 04:33 UTC, OofAlt commented
fixed the bugs, didn't have to change much fortunately. Bot should only turn when a lookingTask is running

2021-08-07 21:58 UTC, rom1504 requested changes
either do a custom callbackify to make the param really optional or this is a breaking change that will need to wait for callback to be removed

2021-08-15 12:59 UTC, rom1504 commented
blocked by  #1482

2022-08-07 15:06 UTC, rom1504 commented
can you please fix conflicts ?

2022-10-26 04:31 UTC, closed without merging