Added attachEntity and detatchEntity functionality to versions past 1.8 #2819
PrismarineJS/mineflayer pull request #2820
Opened 2022-10-28 22:49 UTC by drakemj

As mentioned in #2819, just added an event for `set_passengers` in entities.js. Attaching and detaching now works as expected as far as triggering the events; however, the return values only include the vehicle. This is because `set_passengers` itself has no way of tracking the previous passenger state of the vehicle unlike `attach_entity`, and thus there is no way with just that function to be able to tell which entity has been attached/detached in certain cases.

2022-11-20 01:02 UTC, rom1504 commented on lib/plugins/entities.js
> +    if (!entity.passengerCount) {
could you add a comment explaining these branches ? it's highly non intuitive

2023-02-12 05:15 UTC, extremeheat requested changes

2023-02-12 05:15 UTC, extremeheat commented on lib/plugins/entities.js
> +      delete entity.passengerCount
Why the need to delete and not leave this value at 0?

2023-02-12 05:15 UTC, extremeheat commented on lib/plugins/entities.js
> +      entity.passengerCount = 2
Why not leave this as passengers.length?

2023-03-04 18:01 UTC, rom1504 commented
too old

2023-03-04 18:01 UTC, closed without merging