Add dimensionChange event
PrismarineJS/mineflayer pull request #3275
Opened 2024-01-04 21:08 UTC by IceTank

This event is useful as not all emitted respawn events mean a dimension change. This event also emits when a login packet is send as not all login packets cause a spawn event to be emitted.

This pull request also changes some inconsistencies in how dimensions are named. Previously the nether and the end where sometimes refereed to as nether and end instead of the_nether and the_end. Minecraft always named them as the_nether and the_end.
This pull request also fixes a bug where worldName would sometimes not change after a dimension has been changed.

2024-01-05 02:49 UTC, IceTank commented
I fixed failing tests locally. Can push later.

2024-01-06 17:25 UTC, rom1504 commented
waiting for fix

2024-01-07 19:14 UTC, rom1504 commented
/fixlint

2024-01-07 19:24 UTC, rom1504 commented
CI is failing, errors are relevant to the change here

2024-01-07 22:31 UTC, IceTank commented
Yes Ill look more into it. It works for me but maybe the github runner needs more time for some stuff.

2024-01-07 22:55 UTC, rom1504 commented
```
  2) mineflayer_external 1.14.4v
       nether nether dimension change event:

      AssertionError [ERR_ASSERTION]: 'overworld' == 'the_nether'
```

and raytrace test failures

doesn't seem like timing to me

2024-05-11 19:32 UTC, MrFiend179 requested changes

2024-05-11 19:32 UTC, MrFiend179 commented on lib/plugins/blocks.js
> +  '-1': 'minecraft:the_nether',
are you sure its **the_nether** and not **world_nether**?

2024-05-11 21:10 UTC, extremeheat commented
I updated the tests to use the proper assertion methods, so it's easier to see where the problem are.

```
2024-05-11T20:56:03.7738923Z   2) mineflayer_external 1.14.4v
2024-05-11T20:56:03.7739595Z        nether nether dimension change event:
2024-05-11T20:56:03.7740063Z 
2024-05-11T20:56:03.7741683Z       AssertionError [ERR_ASSERTION]: 'overworld' == 'the_nether'
2024-05-11T20:56:03.7742580Z       + expected - actual
2024-05-11T20:56:03.7742982Z 
2024-05-11T20:56:03.7743194Z       -overworld
2024-05-11T20:56:03.7743640Z       +the_nether
2024-05-11T20:56:03.7744033Z       
2024-05-11T20:56:03.7744812Z       at /home/runner/work/mineflayer/mineflayer/test/externalTests/nether.js:80:12
```

2025-01-19 15:27 UTC, rom1504 commented
Old closing

2025-01-19 15:27 UTC, closed without merging